### ISSUE TITLE
about query

### ISSUE THREAD

**Issue by aznikline** [NEU-Gou/DukeReID#2]
hi!
could you tell me how to split the dataset to train/val and query?

**Comment by NEU-Gou** [comment]
After you download and extract the dataset, you should see a .mat file containing the partition information. Please read through the readme for more information.

**Comment by aznikline** [comment]
ok...but I can't find the keyword like 'probe' or something...
and I don't know what 64 means.

Mengran Gou <notifications@github.com> 于2019年4月13日周六 下午10:01写道：

**Comment by aznikline** [comment]
ok...but I can't find the keyword like 'probe' or something...
and I don't know what 64 means.
